version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: react-form-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-react_form_db}
      MYSQL_USER: ${MYSQL_USER:-react_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-react_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - react-form-network

  # Adminer for database management
  adminer:
    image: adminer:latest
    container_name: react-form-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - react-form-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: react-form-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER:-react_user}:${MYSQL_PASSWORD:-react_password}@mysql:3306/${MYSQL_DATABASE:-react_form_db}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    depends_on:
      - mysql
    networks:
      - react-form-network
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: react-form-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
    depends_on:
      - backend
    networks:
      - react-form-network
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: npm run dev -- --host 0.0.0.0 --port 3000

volumes:
  mysql_data:

networks:
  react-form-network:
    driver: bridge 