name: Build and Test React App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  buld_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x, 22.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: pnpm install, build and test
        run: |
          pnpm install --frozen-lockfile
          pnpm run build --if-present
          pnpm test
